# Data Preprocessing 

## Importing the libraries

In [32]:


import numpy as np

import pandas as pd

## Importing the dataset

In [33]:
dataset =pd.read_csv('Data.csv')
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:,-1].values

In [34]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [35]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [36]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])


In [37]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [40]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [41]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [42]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Feature Scaling

In [44]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x[:, 4:]= sc.fit_transform(x[: , 4: ])

In [45]:
print(x)

[[0.0 1.0 0.0 0.0 0.758874361590019 0.7494732544921677]
 [1.0 0.0 0.0 1.0 -1.7115038793306814 -1.4381784072687531]
 [1.0 0.0 1.0 0.0 -1.2755547779917342 -0.8912654918285229]
 [1.0 0.0 0.0 1.0 -0.1130238410878753 -0.253200423814921]
 [1.0 0.0 1.0 0.0 0.17760889313808945 6.632191985654332e-16]
 [0.0 1.0 0.0 0.0 -0.5489729424268225 -0.5266568815350361]
 [1.0 0.0 0.0 1.0 0.0 -1.0735697969752662]
 [0.0 1.0 0.0 0.0 1.3401398300419485 1.3875383225057696]
 [1.0 0.0 1.0 0.0 1.6307725642679132 1.7521469327992565]
 [0.0 1.0 0.0 0.0 -0.2583402082008577 0.29371249162530916]]
